# app/sample_data/budget_samples.py

from datetime import date

sample_budgets = [
    {
        "expense_type": "expense",
        "category_name": "食費",
        "amount": 1500,
        "date": date(2025, 4, 3),
        "memo": "昼食",
    },
    {
        "expense_type": "expense",
        "category_name": "交通費",
        "amount": 800,
        "date": date(2025, 4, 3),
        "memo": "電車",
    },
    {
        "expense_type": "expense",
        "category_name": "娯楽",
        "amount": 2000,
        "date": date(2025, 4, 10),
        "memo": "映画",
    },
    {
        "expense_type": "income",
        "category_name": "給料",
        "amount": 250000,
        "date": date(2025, 4, 25),
        "memo": "4月分",
    },
    {
        "expense_type": "income",
        "category_name": "その他収入",
        "amount": 12000,
        "date": date(2025, 4, 12),
        "memo": "ライティング",
    },
    {
        "expense_type": "expense",
        "category_name": "日用品",
        "amount": 300,
        "date": date(2025, 4, 12),
        "memo": "洗剤",
    },
    {
        "expense_type": "expense",
        "category_name": "医療",
        "amount": 3500,
        "date": date(2025, 4, 15),
        "memo": "診察",
    },
    {
        "expense_type": "expense",
        "category_name": "光熱費",
        "amount": 7200,
        "date": date(2025, 4, 5),
        "memo": "電気代",
    },
    {
        "expense_type": "expense",
        "category_name": "家賃",
        "amount": 85000,
        "date": date(2025, 4, 1),
        "memo": "4月分",
    },
    {
        "expense_type": "expense",
        "category_name": "食費",
        "amount": 1100,
        "date": date(2025, 4, 6),
        "memo": "夕食",
    },
    {
        "expense_type": "expense",
        "category_name": "教育",
        "amount": 4500,
        "date": date(2025, 4, 8),
        "memo": "参考書",
    },
    {
        "expense_type": "expense",
        "category_name": "通信費",
        "amount": 3200,
        "date": date(2025, 4, 9),
        "memo": "スマホ",
    },
    {
        "expense_type": "income",
        "category_name": "副業",
        "amount": 18000,
        "date": date(2025, 4, 18),
        "memo": "デザイン案件",
    },
    {
        "expense_type": "expense",
        "category_name": "交際費",
        "amount": 5000,
        "date": date(2025, 4, 7),
        "memo": "飲み会",
    },
    {
        "expense_type": "expense",
        "category_name": "その他",
        "amount": 2400,
        "date": date(2025, 4, 11),
        "memo": "雑費",
    },
    {
        "expense_type": "expense",
        "category_name": "食費",
        "amount": 980,
        "date": date(2025, 4, 14),
        "memo": "ランチ",
    },
    {
        "expense_type": "income",
        "category_name": "投資収入",
        "amount": 22000,
        "date": date(2025, 4, 16),
        "memo": "配当金",
    },
    {
        "expense_type": "expense",
        "category_name": "貯金",
        "amount": 30000,
        "date": date(2025, 4, 20),
        "memo": "毎月の積立",
    },
    {
        "expense_type": "expense",
        "category_name": "医療",
        "amount": 1500,
        "date": date(2025, 4, 22),
        "memo": "薬",
    },
    {
        "expense_type": "income",
        "category_name": "ボーナス",
        "amount": 100000,
        "date": date(2025, 5, 28),
        "memo": "春の賞与",
    },
]
