"""empty message

Revision ID: c8854ae78317
Revises: 2b6a4b63bd11
Create Date: 2025-04-08 17:55:02.595165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8854ae78317'
down_revision = '2b6a4b63bd11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expence_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('memo', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_column('memo')
        batch_op.drop_column('date')
        batch_op.drop_column('expence_type')

    # ### end Alembic commands ###
